// <auto-generated />
using Microsoft.JSInterop;
using shopping.web.Helpers;

namespace shopping.web.JavaScript
{
    public partial class CompJavaScript
    {
        private string MensajeConfirmacion = "Esta seguro?";
        private bool ConfirmarResultado { get; set; }

        private async Task DemoConfirmacion(string mensaje)
        {
            ConfirmarResultado = await JsRuntime.InvokeAsync<bool>("confirm", mensaje);
        }

        // Metodos para Toastr
        private async Task DemoSuccess()
        {
            // await JsRuntime.InvokeVoidAsync("ShowToastr", "success", "Tarea completada.");
            await JsRuntime.ToastrSuccess("Tarea completada.");
        }

        private async Task DemoError()
        {
            //await JsRuntime.InvokeVoidAsync("ShowToastr", "error", "Error completando tarea.");
            await JsRuntime.ToastrError("Error completando tarea.");
        }

        // Metodos para Swal
        private async Task DemoSuccessSwal()
        {
            await JsRuntime.InvokeVoidAsync("ShowSwal", "success", "Tarea completada.");
        }

        private async Task DemoErrorSwal()
        {
            await JsRuntime.InvokeVoidAsync("ShowSwal", "error", "Error completando tarea.");
        }
    }
}