// <auto-generated />
using Microsoft.AspNetCore.Components;
using shopping.web.DTOs;
using shopping.web.Interfaces;
using shopping.web.Repositorios;

namespace shopping.web.Pages.Categorias
{
    public partial class CompEditarCategoria
    {
        [Parameter]
        public int? Id { get; set; }
        private CategoriaDto CategoriaDto { get; set; } = new CategoriaDto();

        protected override async Task OnInitializedAsync()
        {
            if(Id != null)
            {
                CategoriaDto = await MyCategoriaRepositorio.GetCategoria(Id.Value);
            }
            
        }


        private async Task ManejadorOnEditarCategoria()
        {
            try
            {
                var NombreCategoria = await MyCategoriaRepositorio.NombreCategoriaExiste(CategoriaDto.NombreCategoria);
                if (NombreCategoria != null) // Exste, no actualiza
                {
                    return;
                }

                // No existe, actualiza
                var EditaCategoria = await MyCategoriaRepositorio.ActualizarCategoria(CategoriaDto.CategoriaId, CategoriaDto);
                NavigationManager.NavigateTo("categorias");
            }
            catch (Exception ex)
            {

                throw;
            }
            
            //var NombreCategoria = await MyCategoriaRepositorio.NombreCategoriaExiste(CategoriaDto.NombreCategoria);

            //if (NombreCategoria != null)
            //{
            //    return;
            //}

            //var CrearCategoria = await MyCategoriaRepositorio.CreaCategoria(CategoriaDto);
            //NavigationManager.NavigateTo("categorias");
        }
    }
}