// <auto-generated />
using shopping.web.DTOs;
using shopping.web.Repositorios;

namespace shopping.web.Pages.Categorias
{
    public partial class CompCrearCategoria
    {
        private CategoriaDto CategoriaDto { get; set; } = new CategoriaDto();

        private async Task ManejadorOnCrearCategoria()
        {
            var NombreCategoria = await MyCategoriaRepositorio.NombreCategoriaExiste(CategoriaDto.NombreCategoria);
            
            if(NombreCategoria != null)
            {
                return;
            }

            var CrearCategoria = await MyCategoriaRepositorio.CreaCategoria(CategoriaDto);
            NavigationManager.NavigateTo("categorias");
        }
    }
}