// <auto-generated />
using shopping.web.DTOs;


namespace shopping.web.Pages.Categorias
{
    public partial class CompCategorias
    {
        private IEnumerable<CategoriaDto> CategoriaDto {  get; set; } = new List<CategoriaDto>();

        protected override async Task OnInitializedAsync()
        {
            try
            {
                CategoriaDto = await MyCategoriaRepositorio.GetAllCategorias();
            }
            catch (Exception ex)
            {

                throw;
            }
            
        }

        private async Task ManejadorOnBorrar(int categoriaId) { }
    }
}