// <auto-generated />
using shopping.web.DTOs;

namespace shopping.web.Pages.Articulos
{
    public partial class CompArticulos
    {
        private IEnumerable<ArticuloDto> ArticuloDto { get; set; } = new List<ArticuloDto>();
        private async Task ManejadorOnBorrar(int categoriaId) { }

        protected override async Task OnInitializedAsync()
        {
            try
            {
                ArticuloDto = await MyArticuloRepositorio.GetAllArticulo();
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}