// <auto-generated />
using shopping.web.DTOs;
using shopping.web.Helpers;


namespace shopping.web.Pages.Articulos
{
    public partial class CompCrearArticulo
    {
        private ArticuloDto ArticuloDto { get; set; } = new ArticuloDto();

        private async Task ManejadorOnCrearPropiedad()
        {
            //var NombreCategoria = await MyCategoriaRepositorio.NombreCategoriaExiste(CategoriaDto.NombreCategoria);

            //if (NombreCategoria != null)
            //{
            //    // Categoria duplicada
            //    await JsRuntime.ToastrError("El nombre de la categoria ya existe.");
            //    return;
            //}

            //var CrearCategoria = await MyCategoriaRepositorio.CreaCategoria(CategoriaDto);
            //await JsRuntime.ToastrSuccess("Categoria creada correctamente.");
            //NavigationManager.NavigateTo("categorias");
        }
    }
}